name: gischain
channels:
  - http://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - anaconda
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - matplotlib-base=3.7.1=py311h2bf763f_0
  - pip:
      - numpy==1.26.0
      - dashscope==1.13.3
      - geopandas==0.13.2
      - gdal==3.7.2
      - zhipuai==1.0.7
      - openai==0.28.1
      - pygraphviz==1.11
